#!/bin/bash

mkdir Ressources 2>/dev/null

PATH_core="/Users/dom/Documents/Projets/TYPO3/Core/typo3_trunk_dfeyer/typo3"
PATH_l10n="/Users/dom/Sites/dev/sandbox.typo3/typo3conf/l10n"

function getLLXMLList() {
  find ${PATH_core}/sysext/$1 -name "locallang*.xml"
}

function getLanguageList() {
  ls -l ${PATH_l10n}/ | egrep "^d" | awk "{print \$9}" | sed s/\\///
}

function getExtensionList() {
  ls -l ${PATH_core}/sysext/ | egrep "^d" | awk "{print \$9}" | sed s/\\///
}

function convert()
{
  if [ "$2" = "default" ]; then
    local target="\"\""
    local output="Ressources/xliff/en/${4}$(echo $3 | sed s/\.xml$/\.xlf/)"
	mkdir -p Ressources/xliff/en/${4} 2>/dev/null
  else
    local target="$2"
    local output="Ressources/xliff/$(echo ${4} | sed "s#$EXTENSION/#$EXTENSION/$LANG/#")$(echo $(basename $target) | sed -e s/\.xml$/\.xlf/ | sed -e s/^$5\.//)"
	mkdir -p Ressources/xliff/$(echo ${4} | sed "s#$EXTENSION/#$EXTENSION/$LANG/#") 2>/dev/null
  fi

  local source="$3"
  
  #echo $output
  xsltproc --stringparam source $target \
    --stringparam date "$(date -u)" \
	--stringparam lang $5 \
	--stringparam extension $1 \
    xml2xliff.xsl $source > $output

}

for EXTENSION in $(getExtensionList); do
	echo
	echo "Processing extension $EXTENSION ..."
	# Generate target XLIFF
	for LANG in $(getLanguageList); do 
		echo
		echo "Processing language: $LANG"
		for source in $(getLLXMLList $EXTENSION); do
		  llfilename=$(echo $source | sed s#${PATH_core}/sysext/## | sed s/\\/locallang/\\/$LANG\.locallang/)
		  llfilepath=$(echo $llfilename | sed s/$(basename $llfilename)//)
		  target="$PATH_l10n/$LANG/$llfilename"
		  if [ -f $source ] && [ -f $target ]; then
		    echo "[info] $(basename $source) -> $(basename $target)"
		    convert $EXTENSION $target $source $llfilepath $LANG
		  #else
		    #echo "[warning] File missing ($(basename $source) -> $(basename $target))"
		  fi
		done
	done
	
	# Generate source XLIFF
	for source in $(getLLXMLList $EXTENSION); do
		llfilename=$(echo $source | sed s#${PATH_core}/sysext/## | sed s/\\/locallang/\\/$LANG\.locallang/)
		llfilepath=$(echo $llfilename | sed s/$(basename $llfilename)//)
		outputdirectory="Ressources/xliff/$(echo ${llfilepath} | sed "s#$EXTENSION/#$EXTENSION/en/#")"
		mkdir -p $outputdirectory 2>/dev/null
		output="$outputdirectory$(echo $(basename $source) | sed -e s/\.xml$/\.xlf/)"
		xsltproc --stringparam source "" \
			--stringparam lang $LANG \
			--stringparam extension $EXTENSION \
		    --stringparam date "$(date -u)" \
		    xml2xliff.xsl $source > $output 2>/dev/null
	done
done 

exit 0
