#!/bin/bash

PATH_site=$1
PATH_core="$PATH_site/typo3"
PATH_l10n="$PATH_site/typo3conf/l10n"

if [ ! -d $PATH_site ] || [ ! -d $PATH_core ] || [ ! -d $PATH_i10n ]; then
  echo
  echo "Not a TYPO3 installation, please check your path ..."
  echo
  exit 1
fi

. ./functions

for XLF_FILE in $(find ./Resources/xliff/*/en -name "*.xlf"); do
  EXTENSION=$(echo $XLF_FILE | sed s#Resources/xliff/## | cut -d/ -f1)
  SOURCE_FILE=$(echo $XLF_FILE | sed s#Resources/xliff/$EXTENSION/en/##)
  XML_FILE=$(echo $SOURCE_FILE | sed s/\.xlf/\.xml/)

  #
  # Replace source XML file
  echo
#  if [ -f $PATH_site/typo3/sysext/$EXTENSION/$XML_FILE ]; then
#    rm $PATH_site/typo3/sysext/$EXTENSION/$XML_FILE
#  fi
  cp -f $XLF_FILE $PATH_site/typo3/sysext/$EXTENSION/$SOURCE_FILE

  #
  # Create Language pack

  for LANG in $(getLanguageList); do
    createLanguagePack $EXTENSION $LANG $SOURCE_FILE
  done

done


